### ISSUE TITLE
Programlayıcı olarak bisikletlerin işlek noktalardan uzak bırakılıp kullanıcıların erişimini zorlaştırmasını çözmeliyim

### ISSUE THREAD

**Issue by Theieyrre** [dab2m/BikePass_Android#11]
Bisiklet bir şekilde işlek noktalardan uzağa giderse ve oraya
bırakılırsa diğer kullanıcıların erişimi zorlaşır. İşlek noktaları tespit etmeli ve bisikletleri buraya bırakılmasına teşvik etmeliyim
	~Veritabanında işlek noktalar tablosu kurulmalı
		-> id
		-> nokta adı
		-> lat long koordinatları
		-> radius miktarı
		-> sıklık oranı columnları olmalı Her bisiklet kiralandığında veya kullanımı bittiğinde eğer bu alan içerisinde ise sıklık miktarını arttırmalıyız. Bu alan içine bırakıldığı zaman kredi dönülmeli. *Kredi miktarı sıklık sayısı ile orantılı olmalı*~
	*Android’de bisiklet kullanılırken map sayfası açılabilmeli ve kullanıcı bu işlek noktaları görüntüleyip oraya bırakmayı amaçlamalı*

**Comment by cagdasgerede** [comment]
Bunun #30 dan ne fark var? https://github.com/dab2m/BikePass_Web/issues/30
