### ISSUE TITLE
As a developer, login and register informations should be send via API given from website

### ISSUE THREAD

**Issue by Theieyrre** [dab2m/BikePass_Android#2]
In Sign-Up page, users informations should be send via REST API to register a new user to database. API should status if register is done or cancelled. Android app should decide for given status if user should continue or re-enter new details

In Sign-In page, users informations should be verified via REST API for given username and password either user can enter or not. Android app should decide for given status as well

Design for both Sign-Up and Sign-In is given below ( Since they are quite similar only change texts inside boxes)
![signup](https://user-images.githubusercontent.com/43235845/72516126-3a0b7000-3862-11ea-8484-98f6eaee5143.PNG)

**Comment by dilandogann** [comment]
Login and registration is succesfully developed
